[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-starstream"
description = "Starstream grammar for tree-sitter"
version = "0.0.0"
keywords = ["incremental", "parsing", "tree-sitter", "starstream"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Paima Studios" }]
requires-python = ">=3.10"
license.text = "MIT/Apache-2.0"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/paimastudios/starstream"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
