name = "Starstream"
grammar = "starstream"
path_suffixes = ["star"]
line_comments = ["// ", "/// "]
autoclose_before = ";:.,=}])>"
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  # { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
    "comment",
  ] },
]
tab_size = 4
